# Generated by Django 5.0 on 2023-12-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_comments_todolist_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='comments',
            field=models.ManyToManyField(blank=True, to='client.comment'),
        ),
    ]
