# Generated by Django 5.0 on 2023-12-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_todolist_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-name'], 'verbose_name': 'Hello', 'verbose_name_plural': 'Hellooooo'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='changed_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
