# Generated by Django 5.0 on 2023-12-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_comment_changed_at_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'ACtive'), ('archived', 'Archived')], default='active', max_length=255),
        ),
    ]
